// Code generated by tygo. DO NOT EDIT.

//////////
// source: common.go

export interface Dataset {
  name: string;
  dsorg: string;
  volser: string;
}
export interface DsMember {
  name: string;
}
export interface UssItem {
  name: string;
  isDir: boolean;
}
export interface Job {
  id: string;
  name: string;
  status: string;
  retcode: string;
}
export interface Spool {
  id: number /* int */;
  ddname: string;
  stepname: string;
  dsname: string;
  procstep: string;
}

//////////
// source: messages.go

export interface CommandRequest {
  command: string;
}
export interface ListDatasetsRequest extends ListOptions, ListDatasetOptions {
  command: "listDatasets";
  pattern: string;
  attributes?: boolean;
}
export interface ListDsMembersRequest extends ListOptions, ListDatasetOptions {
  command: "listDsMembers";
  dataset: string;
}
export interface ListFilesRequest {
  command: "listFiles";
  fspath: string;
  ListOptions: ListOptions;
}
export interface ListJobsRequest extends ListOptions {
  command: "listJobs";
  owner?: string;
  prefix?: string;
  status?: string;
}
export interface ListSpoolsRequest {
  command: "listSpools";
  jobId: string;
}
export interface ReadDatasetRequest {
  command: "readDataset";
  encoding?: string;
  dataset: string;
}
export interface ReadFileRequest {
  command: "readFile";
  encoding?: string;
  path: string;
}
export interface ReadSpoolRequest {
  command: "readSpool";
  encoding?: string;
  dsnKey: number /* int */;
  jobId: string;
}
export interface GetJclRequest {
  command: "getJcl";
  jobId: string;
}
export interface WriteDatasetRequest {
  command: "writeDataset";
  encoding?: string;
  dataset: string;
  contents: string;
}
export interface WriteFileRequest {
  command: "writeFile";
  encoding?: string;
  path: string;
  contents: string;
}
export interface ReadDatasetResponse {
  encoding?: string;
  dataset: string;
  data: Buffer | string;
}
export interface ReadFileResponse {
  encoding?: string;
  path: string;
  data: Buffer | string;
}
export interface ReadSpoolResponse {
  encoding?: string;
  dsnKey: number /* int */;
  jobId: string;
  data: Buffer | string;
}
export interface WriteDatasetResponse {
  success: boolean;
  dataset: string;
}
export interface WriteFileResponse {
  success: boolean;
  path: string;
}
export interface ListDatasetsResponse {
  items: Dataset[];
  returnedRows: number /* int */;
}
export interface ListDsMembersResponse {
  items: DsMember[];
  returnedRows: number /* int */;
}
export interface ListFilesResponse {
  items: UssItem[];
  returnedRows: number /* int */;
}
export interface ListJobsResponse {
  items: Job[];
}
export interface ListSpoolsResponse {
  items: Spool[];
}
export interface GetJclResponse {
  jobId: string;
  data: string;
}
export interface IssueConsoleRequest {
  command: "consoleCommand";
  commandText: string;
  consoleName: string;
}
export interface IssueConsoleResponse {
  data: string;
}
export interface RestoreDatasetRequest {
  command: "restoreDataset";
  dataset: string;
}
export interface RestoreDatasetResponse {
  success: boolean;
}

//////////
// source: options.go

export interface ListOptions {
  maxItems?: number /* int */;
  responseTimeout?: number /* int */;
}
export interface ListDatasetOptions {
  start?: string;
}
