activeProfile: default

profiles:
  default:
    # Name of Zowe SSH profile used to connect to z/OS
    # If you don't have Zowe profiles, run `zowe config init` to create a team configuration file.
    # Or uncomment the section below to define SSH config inline rather than using a Zowe profile.
    sshProfile: ssh
    # sshProfile:
    #   host: example.com
    #   port: 22
    #   user: ibmuser
    #   privateKey: /Users/ibmuser/.ssh/id_rsa
    #   # password: password  # Use password instead of private key

    # USS directory on z/OS where native code is built
    deployDir: ~/zowe-native-proto

    # Environment variables to set for the `go build` command
    goBuildEnv: 'GOINSECURE="*" GOPROXY=direct'  # Allow fetching Go dependencies

    # Command to run before building the native code
    # preBuildCmd: '. ~/entrypoint.sh'  # Run script to configure build environment
