// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"
//////////
// source: requests.go

export interface IssueConsoleRequest {
  command: "consoleCommand";
  commandText: string;
  consoleName: string;
}

//////////
// source: responses.go

export interface IssueConsoleResponse {
  data: string;
}
