// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"
//////////
// source: requests.go

export interface IssueConsoleRequest {
  command: "consoleCommand";
  commandText: string;
  consoleName: string;
}
export interface IssueTsoRequest {
  command: "tsoCommand";
  commandText: string;
}
export interface IssueUnixRequest {
  command: "unixCommand";
  commandText: string;
}

//////////
// source: responses.go

export interface IssueConsoleResponse {
  data: string;
}
export interface IssueTsoResponse {
  data: string;
}
export interface IssueUnixResponse {
  data: string;
}
