/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// Code generated by tygo. DO NOT EDIT.

//////////
// source: common.go

export interface CommandRequest {
    command: string;
}
export interface Dataset {
    name: string;
    dsorg: string;
    volser: string;
}
export interface DsMember {
    name: string;
}
export interface UssItem {
    name: string;
    isDir: boolean;
}
export interface Job {
    id: string;
    name: string;
    status: string;
    retcode: string;
}
export interface Spool {
    id: number /* int */;
    ddname: string;
    stepname: string;
    dsname: string;
    procstep: string;
}

//////////
// source: options.go

export interface ListOptions {
    maxItems?: number /* int */;
    responseTimeout?: number /* int */;
}
export interface ListDatasetOptions {
    start?: string;
}
