// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"

//////////
// source: requests.go

export interface ListDatasetsRequest extends common.ListOptions, common.ListDatasetOptions {
  command: "listDatasets";
  pattern: string;
  attributes?: boolean;
}
export interface ListDsMembersRequest extends common.ListOptions, common.ListDatasetOptions {
  command: "listDsMembers";
  dataset: string;
}
export interface ReadDatasetRequest {
  command: "readDataset";
  encoding?: string;
  dataset: string;
}
export interface WriteDatasetRequest {
  command: "writeDataset";
  encoding?: string;
  dataset: string;
  contents: string;
}
export interface RestoreDatasetRequest {
  command: "restoreDataset";
  dataset: string;
}

//////////
// source: responses.go

export interface WriteDatasetResponse {
  success: boolean;
  dataset: string;
}
export interface RestoreDatasetResponse {
  success: boolean;
}
export interface ReadDatasetResponse {
  encoding?: string;
  dataset: string;
  data: Buffer | string;
}
export interface ListDatasetsResponse {
  items: common.Dataset[];
  returnedRows: number /* int */;
}
export interface ListDsMembersResponse {
  items: common.DsMember[];
  returnedRows: number /* int */;
}
