// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"

//////////
// source: requests.go

export interface ListJobsRequest extends common.ListOptions {
  command: "listJobs";
  owner?: string;
  prefix?: string;
  status?: string;
}
export interface ListSpoolsRequest {
  command: "listSpools";
  jobId: string;
}
export interface ReadSpoolRequest {
  command: "readSpool";
  encoding?: string;
  dsnKey: number /* int */;
  jobId: string;
}
export interface GetJclRequest {
  command: "getJcl";
  jobId: string;
}

//////////
// source: responses.go

export interface ListJobsResponse {
  items: any /* common.Job */[];
}
export interface ListSpoolsResponse {
  items: any /* common.Spool */[];
}
export interface GetJclResponse {
  jobId: string;
  data: string;
}
export interface ReadSpoolResponse {
  encoding?: string;
  dsnKey: number /* int */;
  jobId: string;
  data: Buffer | string;
}
