/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"

//////////
// source: requests.go

export interface ListJobsRequest extends common.ListOptions {
  command: "listJobs";
  /**
   * Filter jobs by matching job owner (optional)
   */
  owner?: string;
  /**
   * Filter jobs by prefix (optional)
   */
  prefix?: string;
  /**
   * Filter jobs by status (optional)
   */
  status?: string;
}
export interface ListSpoolsRequest {
  command: "listSpools";
  /**
   * Job ID to list spools for
   */
  jobId: string;
}
export interface ReadSpoolRequest {
  command: "readSpool";
  /**
   * Desired encoding for the spool file (optional)
   */
  encoding?: string;
  /**
   * Spool ID to read under the given job ID
   */
  spoolId: number /* int */;
  /**
   * Job ID with spools to read from
   */
  jobId: string;
}
export interface GetJclRequest {
  command: "getJcl";
  /**
   * Job ID to get JCL for
   */
  jobId: string;
}
export interface GetStatusRequest {
  command: "getStatus";
  /**
   * Job ID to get status for
   */
  jobId: string;
}
export interface SubmitJobRequest {
  command: "submitJob";
  /**
   * Dataset name w/ contents to submit as JCL
   */
  dsname: string;
}
export interface CancelJobRequest {
  command: "cancelJob";
  /**
   * Job ID to cancel
   */
  jobId: string;
}
export interface DeleteJobRequest {
  command: "deleteJob";
  /**
   * Job ID to cancel
   */
  jobId: string;
}

//////////
// source: responses.go

export interface ListJobsResponse {
  /**
   * List of returned jobs
   */
  items: common.Job[];
}
export interface ListSpoolsResponse {
  /**
   * List of returned spools
   */
  items: common.Spool[];
}
export interface GetJclResponse {
  /**
   * Job ID for the returned JCL
   */
  jobId: string;
  /**
   * JCL contents
   */
  data: string;
}
export interface ReadSpoolResponse {
  /**
   * Desired encoding for the spool file (optional)
   */
  encoding?: string;
  /**
   * Spool ID matching the returned spool contents
   */
  spoolId: number /* int */;
  /**
   * Job ID associated with the returned spool
   */
  jobId: string;
  /**
   * Spool contents
   */
  data: Buffer | string;
}
export interface GetStatusResponse {
  /**
   * List of returned job statuses
   */
  items: common.Job[];
}
export interface SubmitJobResponse {
  /**
   * Whether the job was successfully submitted
   */
  success: boolean;
  /**
   * The data set name where the JCL was read from
   */
  dsname: string;
}
export interface DeleteJobResponse {
  /**
   * Whether the job was successfully deleted
   */
  success: boolean;
  /**
   * The ID for the job that was deletede
   */
  jobId: string;
}
export interface CancelJobResponse {
  /**
   * Whether the job was successfully cancelled
   */
  success: boolean;
  /**
   * The ID for the job that was cancelled
   */
  jobId: string;
}
