// Code generated by tygo. DO NOT EDIT.
/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */
import type * as common from "./common.ts"

//////////
// source: requests.go

export interface ListJobsRequest extends common.ListOptions {
  command: "listJobs";
  owner?: string;
  prefix?: string;
  status?: string;
}
export interface ListSpoolsRequest {
  command: "listSpools";
  jobId: string;
}
export interface ReadSpoolRequest {
  command: "readSpool";
  encoding?: string;
  spoolId: number /* int */;
  jobId: string;
}
export interface GetJclRequest {
  command: "getJcl";
  jobId: string;
}
export interface GetStatusRequest {
  command: "getStatus";
  jobId: string;
}

//////////
// source: responses.go

export interface ListJobsResponse {
  items: common.Job[];
}
export interface ListSpoolsResponse {
  items: common.Spool[];
}
export interface GetJclResponse {
  jobId: string;
  data: string;
}
export interface ReadSpoolResponse {
  encoding?: string;
  spoolId: number /* int */;
  jobId: string;
  data: Buffer | string;
}
export interface GetStatusResponse {
  items: common.Job[];
}
