// Code generated by tygo. DO NOT EDIT.
import type * as common from "./common.ts"

//////////
// source: requests.go

export interface ListFilesRequest extends common.ListOptions {
  command: "listFiles";
  fspath: string;
}
export interface ReadFileRequest {
  command: "readFile";
  encoding?: string;
  path: string;
}
export interface WriteFileRequest {
  command: "writeFile";
  encoding?: string;
  path: string;
  contents: string;
}

//////////
// source: responses.go

export interface ReadFileResponse {
  encoding?: string;
  path: string;
  data: Buffer | string;
}
export interface WriteFileResponse {
  success: boolean;
  path: string;
}
export interface ListFilesResponse {
  items: common.UssItem[];
  returnedRows: number /* int */;
}
