name: Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  changelog:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Changelog Updated
        uses: awharn/check_changelog_action@v1
        with:
          header: "## Recent Changes"
          file: "CHANGELOG.md"
          lerna: true
          ignoreFiles: "__tests__|package.json|package-lock.json|*.md"
